# Generated by Django 2.2.7 on 2021-10-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Listings',
        ),
    ]
