# Generated by Django 2.2.7 on 2021-10-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20211012_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=600),
        ),
    ]
