# Generated by Django 2.2.7 on 2021-10-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
